# Generated by Django 3.0.5 on 2020-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendedTasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskid', models.CharField(max_length=5)),
                ('snumber', models.IntegerField(max_length=6)),
                ('task', models.FileField(upload_to='SendedTasks/tasks/')),
            ],
        ),
    ]
