# Generated by Django 3.0.5 on 2020-04-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sendedtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedtasks',
            name='task',
            field=models.FileField(upload_to=''),
        ),
    ]
