# Generated by Django 3.0.5 on 2020-04-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200422_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedtasks',
            name='snumber',
            field=models.CharField(max_length=6),
        ),
    ]
